services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - "8081:80"
    volumes:
      - ".:/app"
      - "./default.conf:/etc/nginx/conf.d/default.conf"

  phpfpm:
    build:
      context: "./docker"
      dockerfile: "dev.phpfpm.Dockerfile"
    volumes:
      - ".:/app"
      - "./php.ini:/usr/local/etc/php/php.ini"

  pgsql:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "123456"