services:
    php:
        image: "webdevops/php-nginx-dev:8.3-alpine"
        working_dir: "/app"
        env_file:
            - .env.docker
        volumes:
            - ".:/app"
        ports:
            - "${APP_PORT:-80}:80"
    mariadb:
        image: "mariadb:11.5-noble"
        env_file:
            - .env.docker
        ports:
            - "${DB_PORT:-3306}:3306"
