services:
  php:
    image: "php:8.3-alpine"
    volumes:
      - ".:/projeto"
    ports:
      - "8011:80"
    tty: true
    command: "php -S 0.0.0.0:80 -t /projeto"
    environment:
      COMPANY_NAME: "NEXT-GEN PHP"
      SERVICES: "CURSOS|MENTORIAS|TREINAMENTOS"
